version: '3.7'
 
services:
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:80
    environment:
      - FLASK_ENV=development
 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=${REACT_APP_BACKEND_SERVICE_URL}
    depends_on:
      - backend